### ISSUE TITLE
change url

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-pvda-plugin#13]
URL needs to be changed before rebuild ect

https://discourse.pvda.nl/ needs to be https://ledenkamer.pvda.nl

I can do changes @ the admin side

https://meta.discourse.org/t/change-the-domain-name-or-rename-my-discourse/16098?u=techapj

**Comment by kgish** [comment]
Does this require any extra actions on my part?

**Comment by Socioneers** [comment]
Yes, there are a couple of things https://meta.discourse.org/t/change-the-domain-name-or-rename-my-discourse/16098?u=techapj that are back-end related

**Comment by kgish** [comment]
Aha, that makes sense but unfortunately it's not trivial and will take some extra time (which is running out).

**Comment by Socioneers** [comment]
Ok so we will delay that to another day?

R


Raoul
---

+31(0)6 4 66 28 28 3
@socioneers
http://socioneers.com


This email is hosted sustainably.
Important Note: Any unauthorised copying, disclosure or distribution of the material inclosed is strictly forbidden. The Socioneers are registered at the Dutch Chamber of Commerce under number: KVK 09178876

**Comment by kgish** [comment]
This needs to be taken care of before we can do the user import.

**Comment by kgish** [comment]
Changed `containers/app.yml`:
```
DISCOURSE_HOSTNAME: 'discourse.pvda.nl' => 'ledenkamer.pvda.nl' 
```

**Comment by kgish** [comment]
Still homepage is redirecting to discourse.pvda.nl when punching in ledenkamer. The rest of the links seem ok

**Comment by Socioneers** [comment]
https://ledenkamer.pvda.nl/ goes well
ledenkamer.pvda.nl to discourse.pvda.nl
Should we do a search on the server for discourse.pvda.nl ?

**Comment by kgish** [comment]
Could also be nginx server settings, I'll check that as well.

**Comment by Socioneers** [comment]
Great!

**Comment by kgish** [comment]
https://meta.discourse.org/t/change-the-domain-name-or-rename-my-discourse/16098?u=techapj

Checked admin settings as above link describes, but no hits for old `discourse.pvda.com`

**Comment by kgish** [comment]
Will check nginx configuration, you never know.

**Comment by kgish** [comment]
Raoul:
I forgot that I asked michael to check the server. He found the bug, like you thought the nigx thing. Maybe handy to give him access to the git rep. than we all keep track.

**Comment by kgish** [comment]
Michael:

There were multiple problems with nginx.

First there wasn't a symbolic link in /etc/nginx/sites-enabled/ so I created it with

    ln -s /etc/nginx/sites-available/discourse.pvda.nl /etc/nginx/sites-enabled/

Then I edited the config:

Nginx is not only used as a webserver here but also as a reversed proxy and as an endpoint for the ssl encryption.

```
port 80 is redirected to 443 (http -> https)

port 443 is redirected to port 25654 where the docker engine serves the discourse site

server {
        listen 80;
        server_name ledenkamer.pvda.nl;
        return 301 https://ledenkamer.pvda.nl$request_uri;
}
server {
        listen 443 ssl spdy;
        server_name ledenkamer.pvda.nl;
        ssl_certificate /etc/ssl/certs/pvdabundle.crt;
        ssl_certificate_key /etc/ssl/private/pvda.key;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA$
        ssl_prefer_server_ciphers on;
        location / {
                proxy_pass      http://ledenkamer.pvda.nl:25654/;
                proxy_read_timeout      90;
                proxy_redirect  http://ledenkamer.pvda.nl:25654/ https://ledenkamer.pvda.nl/;
        }
}
```

I hope this clears things up :-)

Regards,

Michael Nieuwenweg
