### ISSUE TITLE
Make /about private or hide

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-pvda-plugin#14]
https://discourse.pvda.nl/about
should be not visible for not logged in

**Comment by kgish** [comment]
This is a bit trickier than I first thought, need more time to investigate.

**Comment by kgish** [comment]
In the plugin section of the admin dashboard, I added a new configuration parameter called `pvda_about_hide` which takes a list of sections names (separated by space, comma, colon or semi-colon) which are to be made hidden for users who are not logged in.

This is what the plugin section now looks like:
![admin-dashboard-plugins](https://cloud.githubusercontent.com/assets/79195/18408832/48039c32-773b-11e6-93fc-a2aae56f5e40.png)

This is what the about page will look like with the settings above:
![about-page-not-logged-in](https://cloud.githubusercontent.com/assets/79195/18408838/7281161a-773b-11e6-9d85-f604132fefda.png)

**Comment by kgish** [comment]
@Socioneers : Please verify that this is working on the test server.

**Comment by Socioneers** [comment]
@kgish it works. Great

**Comment by kgish** [comment]
Fixed and ready for production.
