### ISSUE TITLE
Wijzigingen menu-balk

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-pvda-plugin#20]
Menubalk: Alle processen -> Ledendemocratie; Alle Standpunten -> Thema's; (Laatste: ongewijzigd); Steunbetuigingen -> Meest Gesteund;
Mijn Berichten: niet tonen bij niet-ingelogde gebruikers (maar misschien is dat net te complex?)

**Comment by kgish** [comment]
Alle processen -> Ledendemocratie okay.

**Comment by kgish** [comment]
@Socioneers : Is this still relevant?

**Comment by Socioneers** [comment]
No

**Comment by kgish** [comment]
Okay then I will close it.
