### ISSUE TITLE
Text changed with admin panel in test and production

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-pvda-plugin#23]
<img width="1280" alt="screen shot 2016-09-12 at 10 52 33" src="https://cloud.githubusercontent.com/assets/11832800/18430573/6c8c4b9a-78d9-11e6-9a94-583ab737f639.png">
<img width="1280" alt="screen shot 2016-09-12 at 10 57 16" src="https://cloud.githubusercontent.com/assets/11832800/18430574/6c8d5544-78d9-11e6-90bb-9bb11ad55d82.png">

**Comment by kgish** [comment]
@Socioneers : What is this? Still relevant?

**Comment by Socioneers** [comment]
No

**Comment by kgish** [comment]
Okay, then I will close this issue.
