### ISSUE TITLE
Mass remove imported users from test inviroment

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-pvda-plugin#25]
Members that have been imported into test environment have to be removed, because of privacy reasons.

**Comment by kgish** [comment]
I have a delete script for that:

`rake user_importer:clear`

Shall I run it?

-- 
Kiffin Gish
Gouda, The Netherlands

**Comment by kgish** [comment]
Didn't work, try the following:
```
$ rails c
User.destroy_all("active = false")
```

**Comment by Socioneers** [comment]
Can we arrange that active users dont get removed?

Thanks

**Comment by kgish** [comment]
Yes, that's the idea. I'm afraid that Discourse unfortunately doesn't have an "easy" way to delete users in bulk. Looking for a solution...

**Comment by Socioneers** [comment]
Ok pause it for now than. See feed back on docx issue.

Thanks

**Comment by kgish** [comment]
@Socioneers : you mentioned that you could do this by enabling a site setting to remove inactive user.

I would also like to know what you do.

Please do this and close issue when done.

**Comment by Socioneers** [comment]
I did, did not check the result

**Comment by Socioneers** [comment]
michael is working on it

**Comment by kgish** [comment]
```
cd /var/discourse
./launcher enter app
rails c
User.joins(:user_stat).where("user_stats.post_count = 0").destroy_allcd /var/discourse
./launcher enter app
rails c
```

**Comment by kgish** [comment]
I will do this after the next update.

**Comment by kgish** [comment]
Done.

![screenshot from 2016-12-16 20-04-39](https://cloud.githubusercontent.com/assets/79195/21274941/e9e82dde-c3ca-11e6-8db5-13669b9478ad.png)
