### ISSUE TITLE
Remove [Nieuw Onderwerp]-button from homepage

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-pvda-plugin#3]
Remove this button:
![remove-button](https://cloud.githubusercontent.com/assets/79195/18246066/5f10568e-7369-11e6-8702-969737c1ecf4.png)

**Comment by kgish** [comment]
@Socioneers : Please verify this evening (after test server upgrade).

**Comment by Socioneers** [comment]
Yes confirmed

Raoul
---

**Comment by kgish** [comment]
I meant to confirm AFTER this evening that indeed it works as expected.

**Comment by Socioneers** [comment]
right
