### ISSUE TITLE
Document/ motie number doesn't always appear

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-pvda-plugin#32]
The amendment number should appear to the left of the title, but for some reason this does not always happen.

A page refresh makes it reappear, but navigating via some links it will not appear initally.

**Comment by Socioneers** [comment]
After a refresh it does...

**Comment by kgish** [comment]
Yeah, still buggy. I will try and fix it.

**Comment by kgish** [comment]
Fixed => https://github.com/kgish/discourse-pvda-plugin/commit/f4b0be0b97bbc37b5baddfd8406d3fdcbf6c347c
