### ISSUE TITLE
Remove "nieuw onderwerp" in share popup

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-pvda-plugin#33]
See https://github.com/kgish/discourse-annotator-plugin/issues/57.

**Comment by kgish** [comment]
Trying to hide the button when the page loads will not work because it is created dynamically `after` the share-link is clicked.
```
$('#share-link .reply-as-new-topic').hide(); // doesn't work
```
Need to hook click event handler to:
```
<button class="widget-button share no-text">...</button>
```

**Comment by Socioneers** [comment]
This relates only to amendments

**Comment by Socioneers** [comment]
Is not working.
Can we move this to `kgish/discourse-annotator-plugin`, because this only relates to **amendments**

**Comment by kgish** [comment]
Was originally created there, but it is not related to the plugin (which depends on the annotatory.js lib), so we can leave it here.

**Comment by kgish** [comment]
As mentioned in the first post^^^

See: kgish/discourse-annotator-plugin#57.
