### ISSUE TITLE
What to do with annotator-server

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-pvda-plugin#36]
Currently we are still using https://powerful-lowlands-24881.herokuapp.com which is my private Heroku account.

In the long term having an external datastore is probably not what pvda wants.

Need to decide what to do, e.g. internal server setup within the pvda infrastructure.

**Comment by Socioneers** [comment]
Shall we move this issue to kgish/discourse-annotator-plugin?

**Comment by Socioneers** [comment]
moved to: kgish/discourse-annotator-plugin > What to do with annotator-server #78
