### ISSUE TITLE
Maak onderwerp should be maak motie

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-pvda-plugin#39]
Bij Moties: ' Maak Onderwerp' -> ' Maak motie'. (de publiceerknop)

**Comment by Socioneers** [comment]
<img width="423" alt="screen shot 2016-10-20 at 08 31 39" src="https://cloud.githubusercontent.com/assets/11832800/19548556/a60c9aee-969f-11e6-9db1-511af9413807.png">

**Comment by kgish** [comment]
This has been linked to [discourse-annotator issue #86](https://github.com/kgish/discourse-annotator-plugin/issues/86), so close this issue and track there.
