### ISSUE TITLE
Bewerken should be wijzigen

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-pvda-plugin#40]
As it says.

**Comment by Socioneers** [comment]
I don't understand `https://github.com/kgish/discourse-annotator-plugin/issues/81`  should be sufficient.

**Comment by kgish** [comment]
Indeed, this is related to https://github.com/kgish/discourse-annotator-plugin/issues/81.

However, because the translation-specific stuff is the responsibility of the pvda-plugin that's why I created this issue.
