### ISSUE TITLE
Remove or hide the "alle processen" button?

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-pvda-plugin#48]
Remove or hide the "alle processen" button in topmenu

**Comment by Socioneers** [comment]
<img width="1280" alt="screen shot 2016-12-02 at 12 09 15" src="https://cloud.githubusercontent.com/assets/11832800/20832609/6f7e0036-b88b-11e6-9d24-743032f6a0d0.png">

**Comment by kgish** [comment]
This was a previous request, so you want me to disable it completely or show it only on certain pages?

**Comment by Socioneers** [comment]
I only see it on the motie page, so lets try to disable it totally.
