### ISSUE TITLE
Change the lock icon

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-pvda-plugin#49]
Can we change the lock icons @ the categories for other less intimidating icons?

**Comment by Socioneers** [comment]
<img width="245" alt="screen shot 2016-12-02 at 11 41 43" src="https://cloud.githubusercontent.com/assets/11832800/20832568/2cc1e9a6-b88b-11e6-9de1-9c82cf312f2e.png">

**Comment by kgish** [comment]
Please select a nicer looking icon from here: http://fontawesome.io/icons/

**Comment by Socioneers** [comment]
http://fontawesome.io/icon/circle/ <http://fontawesome.io/icon/circle/>

**Comment by kgish** [comment]
The lock icon is used all over the place, did you want to replace it globally or just in certain places?

**Comment by kgish** [comment]
https://meta.discourse.org/t/howto-change-lock-icon-for-restricted-categories/26217

**Comment by kgish** [comment]
![screenshot from 2016-12-04 15-04-09](https://cloud.githubusercontent.com/assets/79195/20866686/f60c51f4-ba32-11e6-83d3-129f6b12e4d6.png)

**Comment by kgish** [comment]
![screenshot from 2016-12-04 15-05-07](https://cloud.githubusercontent.com/assets/79195/20866689/0f485398-ba33-11e6-9b6a-90c4d7ee3c9d.png)

**Comment by Socioneers** [comment]
Looks good. 
Now users won’t be scared that that they should not click on the restricted categories and topics.
