### ISSUE TITLE
Import and creating a users through Users API

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-pvda-plugin#5]
We need to import the member (50.000 users) directory that I have in xls into discourse and create users with a personal password reset token / url that we need to paste back on the xls.
https://meta.discourse.org/t/using-the-api-for-user-management-the-100-user-limit/37562
Needs to be used Wednesday 07/09 ...

**Comment by kgish** [comment]
This is not easy and quite tricky. I only work on the development and test environments, and this will involve changing the production database.

**Comment by kgish** [comment]
@Socioneers

I will need a mapping from the original xls field names to the discourse user attributes, namely:
```
username
created_at
updated_at
name
email
admin
trust_level
date_of_birth
flag_level
ip_address
moderator
blocked
title
uploaded_avatar_id
locale
primary_group_id
staged
```

**Comment by kgish** [comment]
Related to #11.

**Comment by kgish** [comment]
![screenshot from 2016-09-05 22 17 03](https://cloud.githubusercontent.com/assets/79195/18256504/818a2b52-73b6-11e6-976e-4a2b3e8d0e09.png)

**Comment by kgish** [comment]
https://meta.discourse.org/t/problems-with-mailcatcher-in-dev-environment/23412/9
```
Alternate solution: 
1. Access to your email_tokens table
2. Copy value in the token column which is in the same row as your username
3. Paste http://localhost:3000/users/activate-account/your_token_value7 on your browser address bar
4. Will able to activate your account
```

**Comment by kgish** [comment]
See: https://github.com/vindia/discourse_user_importer

**Comment by kgish** [comment]
I've got the user import script working but need to test it first.

You will need to convert the XLXS-file into a CSV-file using ';' (semi-colon) as the separator, for example:
```
Relatienummer;Voornaam;Initialen;Tussenvoegsel;Achternaam;Adres 1: plaats;E-mail (thuis);Stemcode
81505;Wim;W.B.J.;van;Meurs;AMSTERDAM;wim.van.meurs@gmail.com;
...
```
This will be imported in such a way as to create the following new user"
```
name: Wim van Meurs
username:wim.van.meurs
email: wim.van.meurs@gmail.com
```
The other fields will be discarded: `Relatienummer`, `Adres 1: plaats` and `Stemcode`

**Comment by Socioneers** [comment]
Great, does it work with wims details?

**Comment by kgish** [comment]
Yes, but I still need to know which user group I should the imported 
users belong to?

-- 
Kiffin Gish
Gouda, The Netherlands

**Comment by kgish** [comment]
I'm assuming `PvdA`

**Comment by kgish** [comment]
@Socioneers: Please provide me with a list of the first 100 users so that I can check that my script works correctly.

**Comment by Socioneers** [comment]
Ok, still with kids...

**Comment by kgish** [comment]
Created backups:
```
$ pg_dump -xOf /tmp/discourse-backup.sql -d discourse -n public
$ gzip -9 /tmp/discourse-backup.sql
$ tar -czf /tmp/discourse-uploads.tar.gz -C /shared uploads
```

**Comment by kgish** [comment]
Running migrations script:
```
$ rake user_importer:import[/tmp/users.csv] >import.log
```

**Comment by kgish** [comment]
Updated the `user_import.rake` task for the NOK list with corrected fields. See commit: https://github.com/kgish/discourse-pvda-plugin/commit/62fd0619d3ee85d14e2f14685107f3e53dfed39b

Running new migrations script to include these users as well:

    $ rake user_importer:import[/tmp/users-nok.csv] >import.log
