### ISSUE TITLE
User icons should be hidden

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-pvda-plugin#50]
User icons on homepage and category pages are visible after clicking "logo home button" and when you scroll down the page. Should be hidden.

**Comment by Socioneers** [comment]
<img width="1201" alt="screen shot 2016-12-02 at 12 19 23" src="https://cloud.githubusercontent.com/assets/11832800/20832525/f70b6896-b88a-11e6-9dbe-aa9e684c3d4a.png">
<img width="1280" alt="screen shot 2016-12-02 at 12 29 47" src="https://cloud.githubusercontent.com/assets/11832800/20832548/0c25f5d4-b88b-11e6-9809-fe99365b2338.png">

**Comment by kgish** [comment]
Yes indeed, they are initially hidden on page load by simply hiding them, but I will implement a more proper solution for this.

**Comment by kgish** [comment]
Am unable to reproduce. introduced a timer (100ms) which should fix it.
