### ISSUE TITLE
Topics timestap should be hidden.

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-pvda-plugin#51]
topics timestap (16/ maand) behind categories are confusing for people and should be hidden.

**Comment by Socioneers** [comment]
<img width="1172" alt="screen shot 2016-12-02 at 12 16 58" src="https://cloud.githubusercontent.com/assets/11832800/20832486/d4197102-b88a-11e6-9bbd-ff55190f4e6e.png">
<img width="588" alt="screen shot 2016-12-02 at 12 18 07" src="https://cloud.githubusercontent.com/assets/11832800/20832501/e4bab05c-b88a-11e6-88dd-156fec6d7194.png">

**Comment by kgish** [comment]
Always or just on certain pages? An option would be to hide the whole column, is that what you want?

**Comment by Socioneers** [comment]
Hide the whole column, with activity per week/ month/ year

**Comment by kgish** [comment]
Always or just on certain pages?

**Comment by kgish** [comment]
Changed the default to include `th.topics` and `td.topics`:
![screenshot from 2016-12-04 14-42-55](https://cloud.githubusercontent.com/assets/79195/20866574/03bae5f2-ba30-11e6-90ba-20e580fa8c52.png)

**Comment by kgish** [comment]
The second screenshot I could not reproduce, this is what production (and my own development environment) looks like:

![screenshot from 2016-12-04 14-45-53](https://cloud.githubusercontent.com/assets/79195/20866593/7ab25186-ba30-11e6-813c-aa22307bf4f5.png)
