### ISSUE TITLE
Language client.nl.yml

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-pvda-plugin#53]
There's been a new version of dutch language file that needs to be merged with our version.

**Comment by kgish** [comment]
Differences can be found here: 
https://github.com/kgish/discourse-pvda-plugin/commit/33e8e1b603236fd3422b429bd2cc7a7b1dfb7b79

**Comment by Socioneers** [comment]
See my edits. 
[20161215-laguage-RK.txt](https://github.com/kgish/discourse-pvda-plugin/files/654353/20161215-laguage-RK.txt)

In general I will have a final look at language. Some terms developed my my predecessors I want to change. (ledendemocratie for categories)

**Comment by kgish** [comment]
Seems like the version you corrected was not the same as the latest. You can check by viewing the differences between the two attached files:
* [Original](https://github.com/kgish/discourse-pvda-plugin/files/655016/client.nl.org.yml.txt)
* [Latest](https://github.com/kgish/discourse-pvda-plugin/files/655017/client.nl.yml.txt)

**Comment by kgish** [comment]
Tip: next time just make corrections directly into the original, not necessary to list in a separate file. I have the tools to verify changes and merge them.
