### ISSUE TITLE
Right column remove category labels

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-pvda-plugin#56]
Users seem to find the right column useful but the colours making it confusing.

<img width="788" alt="screen shot 2016-12-16 at 12 20 33" src="https://cloud.githubusercontent.com/assets/11832800/21261293/b76dd146-c38a-11e6-8e7e-09be2a382a0a.png">

**Comment by kgish** [comment]
Selector:
```
table > tbody > tr > td.main-link > tr:nth-child(2) > a > \
    span.badge-category.clear-badge.restricted
```

**Comment by kgish** [comment]
Just need to add `.topic-list-latest .badge-category` to the site plugin setting `pvda_always_hidden`

**Comment by Socioneers** [comment]
Looks a lot better, less chaotic!
